# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import phonebook_pb2 as phonebook__pb2


class PhonebookServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddContact = channel.unary_unary(
                '/PhonebookService/AddContact',
                request_serializer=phonebook__pb2.Contact.SerializeToString,
                response_deserializer=phonebook__pb2.Status.FromString,
                )
        self.RemoveContact = channel.unary_unary(
                '/PhonebookService/RemoveContact',
                request_serializer=phonebook__pb2.ContactId.SerializeToString,
                response_deserializer=phonebook__pb2.Status.FromString,
                )
        self.SearchContacts = channel.unary_unary(
                '/PhonebookService/SearchContacts',
                request_serializer=phonebook__pb2.SearchQuery.SerializeToString,
                response_deserializer=phonebook__pb2.Contacts.FromString,
                )
        self.GetContact = channel.unary_unary(
                '/PhonebookService/GetContact',
                request_serializer=phonebook__pb2.ContactId.SerializeToString,
                response_deserializer=phonebook__pb2.Contact.FromString,
                )


class PhonebookServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddContact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveContact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchContacts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PhonebookServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddContact': grpc.unary_unary_rpc_method_handler(
                    servicer.AddContact,
                    request_deserializer=phonebook__pb2.Contact.FromString,
                    response_serializer=phonebook__pb2.Status.SerializeToString,
            ),
            'RemoveContact': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveContact,
                    request_deserializer=phonebook__pb2.ContactId.FromString,
                    response_serializer=phonebook__pb2.Status.SerializeToString,
            ),
            'SearchContacts': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchContacts,
                    request_deserializer=phonebook__pb2.SearchQuery.FromString,
                    response_serializer=phonebook__pb2.Contacts.SerializeToString,
            ),
            'GetContact': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContact,
                    request_deserializer=phonebook__pb2.ContactId.FromString,
                    response_serializer=phonebook__pb2.Contact.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PhonebookService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PhonebookService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddContact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PhonebookService/AddContact',
            phonebook__pb2.Contact.SerializeToString,
            phonebook__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveContact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PhonebookService/RemoveContact',
            phonebook__pb2.ContactId.SerializeToString,
            phonebook__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SearchContacts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PhonebookService/SearchContacts',
            phonebook__pb2.SearchQuery.SerializeToString,
            phonebook__pb2.Contacts.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetContact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PhonebookService/GetContact',
            phonebook__pb2.ContactId.SerializeToString,
            phonebook__pb2.Contact.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
