# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: phonebook.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fphonebook.proto\"i\n\x07\x43ontact\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\x13\n\x0bmiddle_name\x18\x03 \x01(\t\x12\x14\n\x0cphone_number\x18\x04 \x01(\t\x12\x0c\n\x04note\x18\x05 \x01(\t\"\x17\n\tContactId\x12\n\n\x02id\x18\x01 \x01(\x05\"5\n\x0bSearchQuery\x12\r\n\x05query\x18\x01 \x01(\t\x12\x17\n\x0fsearch_in_notes\x18\x02 \x01(\x08\"&\n\x08\x43ontacts\x12\x1a\n\x08\x63ontacts\x18\x01 \x03(\x0b\x32\x08.Contact\"*\n\x06Status\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xb0\x01\n\x10PhonebookService\x12!\n\nAddContact\x12\x08.Contact\x1a\x07.Status\"\x00\x12&\n\rRemoveContact\x12\n.ContactId\x1a\x07.Status\"\x00\x12+\n\x0eSearchContacts\x12\x0c.SearchQuery\x1a\t.Contacts\"\x00\x12$\n\nGetContact\x12\n.ContactId\x1a\x08.Contact\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'phonebook_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CONTACT']._serialized_start=19
  _globals['_CONTACT']._serialized_end=124
  _globals['_CONTACTID']._serialized_start=126
  _globals['_CONTACTID']._serialized_end=149
  _globals['_SEARCHQUERY']._serialized_start=151
  _globals['_SEARCHQUERY']._serialized_end=204
  _globals['_CONTACTS']._serialized_start=206
  _globals['_CONTACTS']._serialized_end=244
  _globals['_STATUS']._serialized_start=246
  _globals['_STATUS']._serialized_end=288
  _globals['_PHONEBOOKSERVICE']._serialized_start=291
  _globals['_PHONEBOOKSERVICE']._serialized_end=467
# @@protoc_insertion_point(module_scope)
